/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Course;

import BLL.Course.OnsiteCourseBLL;
import DAL.Course.Department;
import DAL.Course.OnsiteCourse;
import BLL.Course.DepartmentBLL;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Time;
import java.util.List;

/**
 *
 * @author chris
 */
public class OnsiteCourseEditForm extends javax.swing.JFrame {

    /**
     * Creates new form OnsiteCourseAddGUI
     */
//    private DefaultTableModel tableModel;
    OnsiteCourseBLL osbll;
    OnsiteCourse currentCourse;
    DepartmentBLL dbll = new DepartmentBLL();
    int CourseID;
    OnsiteCourseForm home;

    public OnsiteCourseEditForm(int CourseID) throws SQLException {
        this.setTitle("Edit OnsiteCourse");
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        osbll = new OnsiteCourseBLL();
        currentCourse = osbll.getOs(CourseID);
        try {
            loadComboboxDepartment();
        } catch (SQLException ex) {
            Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.CourseID = CourseID;
        updateCourseDisplay();
    }

    public OnsiteCourseEditForm(int CourseID, OnsiteCourseForm parent, boolean modal) throws SQLException {
        this.setTitle("Edit OnsiteCourse");
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        osbll = new OnsiteCourseBLL();
        currentCourse = osbll.getOs(CourseID);
        home = parent;
        try {
            loadComboboxDepartment();
        } catch (SQLException ex) {
            Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.CourseID = CourseID;
        updateCourseDisplay();
    }

    public void updateCourseDisplay() throws SQLException {
        textField1.setText("" + currentCourse.getCredits());
        textField2.setText(currentCourse.getTitle());
        textField4.setText(currentCourse.getLocation());
        textField5.setText(currentCourse.getDays());
        String time = currentCourse.getTime().toString();
        textField6.setText(time);
        DpComboBox.getModel().setSelectedItem(dbll.getDepartmentName(currentCourse.getDepartmentID()));
    }

    private void loadComboboxDepartment() throws SQLException {
        List<Department> listDP = (List<Department>) dbll.LoadDepartment(1);
        System.out.println(listDP.size());
        for (int i = 0; i < listDP.size(); i++) {
            DpComboBox.addItem(listDP.get(i).getName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSuggestionUI1 = new UI.UI_Item.combobox.ComboSuggestionUI();
        comboSuggestionUI2 = new UI.UI_Item.combobox.ComboSuggestionUI();
        textField1 = new UI.UI_Item.textfield.TextField();
        textField2 = new UI.UI_Item.textfield.TextField();
        textField4 = new UI.UI_Item.textfield.TextField();
        textField5 = new UI.UI_Item.textfield.TextField();
        textField6 = new UI.UI_Item.textfield.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DpComboBox = new UI.UI_Item.combobox.ComboBoxSuggestion();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new UI.UI_Item.button.MyButton();
        btnEdit2 = new UI.UI_Item.button.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });

        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });

        textField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Credits");

        jLabel2.setText("DepartmentID");

        jLabel3.setText("Title");

        jLabel4.setText("Location");

        jLabel5.setText("Time");

        jLabel6.setText("Days");

        DpComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DpComboBoxItemStateChanged(evt);
            }
        });
        DpComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("VNI Greece", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 41, 54));
        jLabel7.setText("EDIT");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(12, 105, 172));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/previous.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderColor(new java.awt.Color(12, 105, 172));
        btnBack.setColor(new java.awt.Color(255, 255, 255));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnEdit2.setBackground(new java.awt.Color(0, 161, 255));
        btnEdit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/diskette.png"))); // NOI18N
        btnEdit2.setText("Edit");
        btnEdit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DpComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField6ActionPerformed

    private void DpComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DpComboBoxActionPerformed

    private void DpComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DpComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DpComboBoxItemStateChanged

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnEdit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit2MouseClicked
        OnsiteCourse os = new OnsiteCourse();
        os.setCredits(Integer.parseInt(textField1.getText()));
        String name = DpComboBox.getSelectedItem().toString();
        int dpid = 0;
        try {
            dpid = dbll.DepartmentID(name);
        } catch (SQLException ex) {
            Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        os.setDepartmentID(dpid);
        os.setTitle(textField2.getText());
        os.setLocation(textField4.getText());
        os.setDays(textField5.getText());
        Time time = Time.valueOf(textField6.getText());
        os.setTime(time);
        os.setCourseID(this.CourseID);
        try {
            if (osbll.editOnsiteCourse(os) > 0) {
                JOptionPane.showMessageDialog(this, "Complete edit OnsiteCourse", "Message", JOptionPane.INFORMATION_MESSAGE);
                home.initTable();
            } else {
                JOptionPane.showMessageDialog(this, "Error edit OnsiteCourse", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(Level.SEVERE, null, ex);
        }
//        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEdit2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnsiteCourseEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.UI_Item.combobox.ComboBoxSuggestion DpComboBox;
    private UI.UI_Item.button.MyButton btnBack;
    private UI.UI_Item.button.MyButton btnEdit2;
    private UI.UI_Item.combobox.ComboSuggestionUI comboSuggestionUI1;
    private UI.UI_Item.combobox.ComboSuggestionUI comboSuggestionUI2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private UI.UI_Item.textfield.TextField textField1;
    private UI.UI_Item.textfield.TextField textField2;
    private UI.UI_Item.textfield.TextField textField4;
    private UI.UI_Item.textfield.TextField textField5;
    private UI.UI_Item.textfield.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
