/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StudentGrade;

import BLL.Course.CourseBLL;
import BLL.StudentBLL;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Ngan
 */
public class StudentGradeStudentIDForm extends javax.swing.JFrame {
    private Object[] stlistID,stlistName;
    public DefaultTableModel model;
    /**
     * Creates new form StudentID
     */
    public StudentGradeStudentIDForm() {
        this.stlistID = readStuID();
        this.stlistName = readStuName();
        initComponents();
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel(Table_search(),0);
        tb2.setModel(model);
        tb2.fixTable(jScrollPane1);
        getContentPane().setBackground(Color.WHITE);
    }
    public Object[] readStuID(){
        StudentBLL stbll = new StudentBLL();
        ArrayList<String> list = stbll.readDSID();
        return list.toArray();
    }
    public Object[] readStuName(){
        StudentBLL stbll = new StudentBLL();
        ArrayList<String> list = stbll.readStudentsName();
        return list.toArray();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb2 = new UI.UI_Item.table.TableDark();
        btnback = new UI.UI_Item.button.MyButton();
        btndetail1 = new UI.UI_Item.button.MyButton();
        cbdetail1 = new UI.UI_Item.combobox.ComboBoxSuggestion();
        cbdetail2 = new UI.UI_Item.combobox.ComboBoxSuggestion();
        btndetail2 = new UI.UI_Item.button.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 414));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 161, 255));
        jLabel1.setText("DETAIL STUDENT");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setPreferredSize(new java.awt.Dimension(166, 40));

        tb2.setForeground(new java.awt.Color(102, 102, 102));
        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Course ID", "Title", "Type", "Grade"
            }
        ));
        tb2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(tb2);

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setForeground(new java.awt.Color(0, 0, 0));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/previous.png"))); // NOI18N
        btnback.setText("BACK");
        btnback.setToolTipText("");
        btnback.setBorderColor(new java.awt.Color(0, 161, 255));
        btnback.setColor(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btndetail1.setBackground(new java.awt.Color(93, 212, 253));
        btndetail1.setForeground(new java.awt.Color(0, 0, 0));
        btndetail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/search (1).png"))); // NOI18N
        btndetail1.setText("DETAIL(ID)");
        btndetail1.setColor(new java.awt.Color(93, 212, 253));
        btndetail1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetail1ActionPerformed(evt);
            }
        });

        cbdetail1.setModel(new javax.swing.DefaultComboBoxModel(stlistID));
        cbdetail1.setForeground(new java.awt.Color(102, 102, 102));
        cbdetail1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        cbdetail2.setModel(new javax.swing.DefaultComboBoxModel(stlistName));
        cbdetail2.setForeground(new java.awt.Color(102, 102, 102));
        cbdetail2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        cbdetail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdetail2ActionPerformed(evt);
            }
        });

        btndetail2.setBackground(new java.awt.Color(93, 212, 253));
        btndetail2.setForeground(new java.awt.Color(0, 0, 0));
        btndetail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/search (1).png"))); // NOI18N
        btndetail2.setText("DETAIL(NAME)");
        btndetail2.setColor(new java.awt.Color(93, 212, 253));
        btndetail2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndetail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetail2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbdetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbdetail2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndetail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btndetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdetail2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetail1ActionPerformed
        CourseBLL bll = new CourseBLL();
        int stdentid = Integer.parseInt(cbdetail1.getSelectedItem().toString());
        ArrayList<String[]> ds = bll.readCourseByStudentIdBLL(stdentid);
        model.setRowCount(0);
        int count = 0 ;
        for(String[] s : ds){
            Vector row=new Vector();
            row.add(count);
            row.add(s[0]);
            row.add(s[1]);
            row.add(s[2]);
            row.add(s[3]);
            model.addRow(row);
            count++;
        }
        tb2.setModel(model);
    }//GEN-LAST:event_btndetail1ActionPerformed

    private void btndetail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetail2ActionPerformed
        CourseBLL bll = new CourseBLL();
        String stdentName = cbdetail2.getSelectedItem().toString();
        ArrayList<String[]> ds = bll.readCourseByStudentNameBLL(stdentName);
        model.setRowCount(0);
        int count = 0 ;
        for(String[] s : ds){
            Vector row=new Vector();
            row.add(count);
            row.add(s[0]);
            row.add(s[1]);
            row.add(s[2]);
            row.add(s[3]);
            model.addRow(row);
            count++;
        }
        tb2.setModel(model);
    }//GEN-LAST:event_btndetail2ActionPerformed

    private void cbdetail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdetail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdetail2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed
    
     public Vector Table_search(){
        Vector head=new Vector();
        head.add("STT");
        head.add("CourseID");
        head.add("Title");
        head.add("Type");
        head.add("Grade");
        return head;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradeStudentIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradeStudentIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradeStudentIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradeStudentIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGradeStudentIDForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.UI_Item.button.MyButton btnback;
    private UI.UI_Item.button.MyButton btndetail1;
    private UI.UI_Item.button.MyButton btndetail2;
    private UI.UI_Item.combobox.ComboBoxSuggestion cbdetail1;
    private UI.UI_Item.combobox.ComboBoxSuggestion cbdetail2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private UI.UI_Item.table.TableDark tb2;
    // End of variables declaration//GEN-END:variables
}
