/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StudentGrade;

import BLL.Course.CourseBLL;
import BLL.StudentBLL;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Ngan
 */
public class StudentGradeCourseIDForm extends javax.swing.JFrame {

    public DefaultTableModel model;
    private Object[] stlistID, stlistTitle;

    /**
     * Creates new form CourseID
     */
    public StudentGradeCourseIDForm() {
        this.stlistID = readCouID();
        this.stlistTitle = readCouTitle();
        initComponents();
        this.setLocationRelativeTo(null);

        model = new DefaultTableModel(Table_search(), 0);
        tb3.setModel(model);
        tb3.fixTable(jScrollPane1);
        getContentPane().setBackground(Color.WHITE);
    }

    public Object[] readCouID() {
        CourseBLL stbll = new CourseBLL();
        ArrayList<String> list = stbll.readDSID();
        return list.toArray();
    }

    public Object[] readCouTitle() {
        CourseBLL stbll = new CourseBLL();
        ArrayList<String> list = stbll.readCourseTitleBLL();
        return list.toArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb3 = new UI.UI_Item.table.TableDark();
        btnback = new UI.UI_Item.button.MyButton();
        btndetail3 = new UI.UI_Item.button.MyButton();
        cbdetailID = new UI.UI_Item.combobox.ComboBoxSuggestion();
        cbdetailName = new UI.UI_Item.combobox.ComboBoxSuggestion();
        btndetail4 = new UI.UI_Item.button.MyButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 414));

        tb3.setForeground(new java.awt.Color(102, 102, 102));
        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Student ID", "Name", "Grade"
            }
        ));
        tb3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(tb3);

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setForeground(new java.awt.Color(0, 0, 0));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/previous.png"))); // NOI18N
        btnback.setText("BACK");
        btnback.setBorderColor(new java.awt.Color(0, 161, 255));
        btnback.setColor(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btndetail3.setBackground(new java.awt.Color(93, 212, 253));
        btndetail3.setForeground(new java.awt.Color(0, 0, 0));
        btndetail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/search (1).png"))); // NOI18N
        btndetail3.setText("DETAIL (ID)");
        btndetail3.setColor(new java.awt.Color(93, 212, 253));
        btndetail3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndetail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetail3ActionPerformed(evt);
            }
        });

        cbdetailID.setModel(new javax.swing.DefaultComboBoxModel(stlistID));
        cbdetailID.setEditable(false);
        cbdetailID.setForeground(new java.awt.Color(102, 102, 102));
        cbdetailID.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        cbdetailName.setModel(new javax.swing.DefaultComboBoxModel(stlistTitle));
        cbdetailName.setForeground(new java.awt.Color(102, 102, 102));
        cbdetailName.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N

        btndetail4.setBackground(new java.awt.Color(93, 212, 253));
        btndetail4.setForeground(new java.awt.Color(0, 0, 0));
        btndetail4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/search (1).png"))); // NOI18N
        btndetail4.setText("DETAIL(TITLE)");
        btndetail4.setColor(new java.awt.Color(93, 212, 253));
        btndetail4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndetail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetail4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 161, 255));
        jLabel2.setText(" DETAIL COURSE");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(166, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbdetailName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btndetail4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbdetailID, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btndetail3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbdetailID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdetailName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndetail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetail3ActionPerformed
        StudentBLL bll = new StudentBLL();
        String courseid = cbdetailID.getSelectedItem().toString();
        ArrayList<String[]> ds = bll.readStudentByCourseIdBll(courseid);
        model.setRowCount(0);
        int count = 0;
        System.out.println(ds.size());
        if (ds.size() > 0) {
            for (String[] s : ds) {
                Vector row = new Vector();
                row.add(count);
                row.add(s[0]);
                row.add(s[1]);
                row.add(s[2]);
                model.addRow(row);
                count++;
            }
        }
        tb3.setModel(model);
    }//GEN-LAST:event_btndetail3ActionPerformed

    private void btndetail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetail4ActionPerformed
        StudentBLL bll = new StudentBLL();
        String courseid = cbdetailName.getSelectedItem().toString();
        ArrayList<String[]> ds = bll.readStudentByCourseTitleBll(courseid);
        model.setRowCount(0);
        int count = 0;
        System.out.println(ds.size());
        if (ds.size() > 0) {
            for (String[] s : ds) {
                Vector row = new Vector();
                row.add(count);
                row.add(s[0]);
                row.add(s[1]);
                row.add(s[2]);
                model.addRow(row);
                count++;
            }
        }
        tb3.setModel(model);
    }//GEN-LAST:event_btndetail4ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    public Vector Table_search() {
        Vector head = new Vector();
        head.add("STT");
        head.add("StudentID");
        head.add("Name");
        head.add("Grade");
        return head;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradeCourseIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradeCourseIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradeCourseIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradeCourseIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGradeCourseIDForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.UI_Item.button.MyButton btnback;
    private UI.UI_Item.button.MyButton btndetail3;
    private UI.UI_Item.button.MyButton btndetail4;
    private UI.UI_Item.combobox.ComboBoxSuggestion cbdetailID;
    private UI.UI_Item.combobox.ComboBoxSuggestion cbdetailName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private UI.UI_Item.table.TableDark tb3;
    // End of variables declaration//GEN-END:variables
}
