/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.StudentGrade;

import BLL.StudentGradeBLL;
import DAL.StudentGrade.StudentGrade;
import UI.MenuForm;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Ngan
 */
public class StudentGradeForm extends javax.swing.JFrame {

    public Vector tblRow;
    MenuForm home;

    /**
     * Creates new form NewJFrame1
     */
    public StudentGradeForm() {
        initComponents();
        btnDoc();
        tb1.fixTable(jScrollPane1);
        getContentPane().setBackground(Color.WHITE);
    }

    public StudentGradeForm(MenuForm parent, boolean modal) {
        initComponents();
        btnDoc();
        tb1.fixTable(jScrollPane1);
        getContentPane().setBackground(Color.WHITE);
        closeChidrentForm(parent, modal);
    }

    public void closeChidrentForm(MenuForm parent, boolean modal) {
        this.setLocationRelativeTo(null);
        this.home = parent;

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                setDefaultCloseOperation(parent.DISPOSE_ON_CLOSE);
                parent.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new UI.UI_Item.table.TableDark();
        btnadd = new UI.UI_Item.button.MyButton();
        btnedit = new UI.UI_Item.button.MyButton();
        btndelete = new UI.UI_Item.button.MyButton();
        btnfind = new UI.UI_Item.button.MyButton();
        btnback = new UI.UI_Item.button.MyButton();
        btndetail = new UI.UI_Item.button.MyButton();
        txtfind = new UI.UI_Item.textfield.SearchField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 414));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 161, 255));
        jLabel1.setText("STUDENT GRADE");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setPreferredSize(new java.awt.Dimension(166, 40));

        tb1.setForeground(new java.awt.Color(102, 102, 102));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Enrollment ID", "Course ID", "Student ID", "Grade", "Student Name", "Course Name"
            }
        ));
        tb1.setToolTipText("");
        tb1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        btnadd.setBackground(new java.awt.Color(93, 212, 253));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/round-add-button (2).png"))); // NOI18N
        btnadd.setText("ADD");
        btnadd.setColor(new java.awt.Color(93, 212, 253));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 161, 255));
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/diskette.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.setColor(new java.awt.Color(0, 161, 255));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(12, 105, 172));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/delete (2).png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setColor(new java.awt.Color(12, 105, 172));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/search (1).png"))); // NOI18N
        btnfind.setText("SEARCH");
        btnfind.setFocusable(false);
        btnfind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setForeground(new java.awt.Color(12, 105, 172));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/previous.png"))); // NOI18N
        btnback.setText("BACK");
        btnback.setBorderColor(new java.awt.Color(12, 105, 172));
        btnback.setColor(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btndetail.setText("ADVENTURE");
        btndetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailActionPerformed(evt);
            }
        });

        txtfind.setText("Search Grade");
        txtfind.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btndetail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailActionPerformed
        new StudentGradeDetailForm(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btndetailActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        StudentGradeAddForm addform = new StudentGradeAddForm(this, rootPaneCheckingEnabled);
        addform.pack();
        addform.setVisible(true);
        addform.setLocationRelativeTo(null);
        addform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if (tblRow != null)
            new StudentGradeEditForm(tblRow).setVisible(true);
        else {
            JOptionPane.showMessageDialog(rootPane, "Choose Student to edit ");
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int i = tb1.getSelectedRow();
        tblRow = new Vector();
        tblRow.add(tb1.getModel().getValueAt(i, 1));
        tblRow.add(tb1.getModel().getValueAt(i, 2));
        tblRow.add(tb1.getModel().getValueAt(i, 3));
        tblRow.add(tb1.getModel().getValueAt(i, 4));
    }//GEN-LAST:event_tb1MouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if (tblRow != null) {
            int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete", "Xóa dịch vụ", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                StudentGradeBLL bll = new StudentGradeBLL();
                if (bll.deleteStudentGradeBLL((int) tblRow.get(0))) {
                    int i = tb1.getSelectedRow();
                    DefaultTableModel model = (DefaultTableModel) tb1.getModel();
                    model.removeRow(i);
                    tb1.setModel(model);
                    JOptionPane.showMessageDialog(rootPane, "Delete successfully ");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Delete failed ");
                }
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Choose a student to delete ");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        if (txtfind.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the grade to find ");
        } else {
            StudentGradeBLL bll = new StudentGradeBLL();
            List list = bll.getStudentGrade(txtfind.getText());
            if (list.size() > 0) {
                DefaultTableModel model = (DefaultTableModel) tb1.getModel();
                model.setRowCount(0);
                int count = 0;
                for (int i = 0; i < list.size(); i++) {
                    List tamp = (List) list.get(count);
                    StudentGrade s = (StudentGrade) tamp.get(0);
                    String name = (String) tamp.get(1);
                    String title = (String) tamp.get(2);
                    Vector row = new Vector();
                    row.add(count);
                    row.add(s.getEnrollmentID());
                    row.add(s.getCourseID());
                    row.add(s.getStudentID());
                    row.add(s.getGrade());
                    row.add(name);
                    row.add(title);
                    model.addRow(row);
                    count++;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not found ");
            }
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnbackActionPerformed

    public static void AddGradeForm(StudentGrade s, String name, String title) {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        int Rowcount = tb1.getRowCount() + 1;
        Vector row = new Vector();
        row.add(Rowcount);
        row.add(s.getEnrollmentID());
        row.add(s.getCourseID());
        row.add(s.getStudentID());
        row.add(s.getGrade());
        row.add(name);
        row.add(title);
        model.addRow(row);
    }

    public static void EditGradeForm(StudentGrade s, String name, String title) {
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        int i = tb1.getSelectedRow();
        model.setValueAt(s.getEnrollmentID(), i, 1);
        model.setValueAt(s.getCourseID(), i, 2);
        model.setValueAt(s.getStudentID(), i, 3);
        model.setValueAt(s.getGrade(), i, 4);
        model.setValueAt(name, i, 5);
        model.setValueAt(title, i, 6);
    }

    public void btnDoc() {
        List list = new ArrayList();
        StudentGradeBLL bus = new StudentGradeBLL();
//        if (StudentGradeBLL.DSSDG == null) {
        list = bus.docDSHD();
//        }
        int count = 1;
        DefaultTableModel model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);
        for (StudentGrade s : StudentGradeBLL.DSSDG) {
            Vector row = new Vector();
            List tamp = (List) list.get(count - 1);
            String name = (String) tamp.get(1);
            String title = (String) tamp.get(2);
            row.add(count);
            row.add(s.getEnrollmentID());
            row.add(s.getCourseID());
            row.add(s.getStudentID());
            row.add(s.getGrade());
            row.add(name);
            row.add(title);
            model.addRow(row);
            count++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGradeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.UI_Item.button.MyButton btnadd;
    private UI.UI_Item.button.MyButton btnback;
    private UI.UI_Item.button.MyButton btndelete;
    private UI.UI_Item.button.MyButton btndetail;
    private UI.UI_Item.button.MyButton btnedit;
    private UI.UI_Item.button.MyButton btnfind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static UI.UI_Item.table.TableDark tb1;
    private UI.UI_Item.textfield.SearchField txtfind;
    // End of variables declaration//GEN-END:variables
}
